// ===== data.js: 게임 정적 데이터 =====

// 직업 정의
const JOBS = {
  warrior:            { name: '전사',           tier: 1, branch: 'warrior', cssClass: 'job-warrior' },
  knight:             { name: '기사',           tier: 2, branch: 'warrior', cssClass: 'job-knight' },
  guardian_knight:    { name: '수호기사',       tier: 3, branch: 'warrior', cssClass: 'job-guardian-knight' },
  gladiator:          { name: '검투사',         tier: 2, branch: 'warrior', cssClass: 'job-gladiator' },
  champion:           { name: '챔피언',         tier: 3, branch: 'warrior', cssClass: 'job-champion' },

  rogue:              { name: '도적',           tier: 1, branch: 'rogue',   cssClass: 'job-rogue' },
  assassin:           { name: '암살자',         tier: 2, branch: 'rogue',   cssClass: 'job-assassin' },
  ninja:              { name: '닌자',           tier: 3, branch: 'rogue',   cssClass: 'job-ninja' },
  hunter:             { name: '사냥꾼',         tier: 2, branch: 'rogue',   cssClass: 'job-hunter' },
  bounty_hunter:      { name: '현상금 사냥꾼', tier: 3, branch: 'rogue',   cssClass: 'job-bounty-hunter' },

  mage:               { name: '마법사',         tier: 1, branch: 'mage',    cssClass: 'job-mage' },
  cathedral_sorcerer: { name: '대성당 술사',    tier: 2, branch: 'mage',    cssClass: 'job-cathedral-sorcerer' },
  cathedral_scholar:  { name: '대성당 학자',    tier: 3, branch: 'mage',    cssClass: 'job-cathedral-scholar' },
  ivory_sorcerer:     { name: '상아탑 술사',    tier: 2, branch: 'mage',    cssClass: 'job-ivory-sorcerer' },
  ivory_sage:         { name: '상아탑 현자',    tier: 3, branch: 'mage',    cssClass: 'job-ivory-sage' },

  healer:             { name: '치유사',         tier: 1, branch: 'healer',  cssClass: 'job-healer' },
  cleric:             { name: '성직자',         tier: 2, branch: 'healer',  cssClass: 'job-cleric' },
  priest:             { name: '신관',           tier: 3, branch: 'healer',  cssClass: 'job-priest' },
  dragon_priest:      { name: '용사제',         tier: 2, branch: 'healer',  cssClass: 'job-dragon-priest' },
  inquisitor:         { name: '심문관',         tier: 3, branch: 'healer',  cssClass: 'job-inquisitor' },
};

// 전직 트리 (jobKey → 가능한 2차 전직 목록)
const JOB_PROMOTIONS = {
  warrior:            ['knight', 'gladiator'],
  knight:             ['guardian_knight'],
  gladiator:          ['champion'],
  rogue:              ['assassin', 'hunter'],
  assassin:           ['ninja'],
  hunter:             ['bounty_hunter'],
  mage:               ['cathedral_sorcerer', 'ivory_sorcerer'],
  cathedral_sorcerer: ['cathedral_scholar'],
  ivory_sorcerer:     ['ivory_sage'],
  healer:             ['cleric', 'dragon_priest'],
  cleric:             ['priest'],
  dragon_priest:      ['inquisitor'],
};

// 전직 비용 (레벨, 골드, 재료)
const PROMOTION_COST = {
  tier2: { level: 10, gold: 2000, material: 10 },
  tier3: { level: 25, gold: 8000, material: 30 },
};

// 특성 목록
const TRAITS = [
  { id: 'iron_body',     name: '강철 몸', desc: '체력 +15%', stat: 'hp',       mult: 0.15 },
  { id: 'berserker',     name: '광전사', desc: '공격력 +15%', stat: 'atk',     mult: 0.15 },
  { id: 'fortress',      name: '요새',   desc: '방어력 +15%', stat: 'def',     mult: 0.15 },
  { id: 'swift',         name: '신속',   desc: '속도 +15%',  stat: 'spd',     mult: 0.15 },
  { id: 'lucky',         name: '행운아', desc: '치명타 확률 +8%', stat: 'crit', mult: 0.08 },
  { id: 'slayer',        name: '처형자', desc: '치명타 데미지 +20%', stat: 'critDmg', mult: 0.20 },
  { id: 'tough',         name: '강인함', desc: '체력 +10%, 방어력 +10%', stat: 'multi', effects: { hp: 0.10, def: 0.10 } },
  { id: 'predator',      name: '포식자', desc: '공격력 +10%, 속도 +10%', stat: 'multi', effects: { atk: 0.10, spd: 0.10 } },
];

// 건물 정의
const BUILDINGS = [
  {
    id: 'headquarters',
    name: '지휘 본부',
    icon: '🏯',
    desc: '길드의 중심. 레벨에 따라 동시 파견 가능한 팀 수가 결정됩니다.',
    effectLabel: (lv) => `파견 슬롯: ${lv}팀`,
    baseCost: { gold: 5000, material: 20 },
    costMult: 2.5,
    maxLevel: 10,
  },
  {
    id: 'lounge',
    name: '대기실',
    icon: '🛋️',
    desc: '모험가들이 쉬는 공간. 레벨당 보유 가능한 모험가 수가 늘어납니다.',
    effectLabel: (lv) => `최대 모험가: ${lv + 2}명`,
    baseCost: { gold: 2000, material: 8 },
    costMult: 1.7,
    maxLevel: 10,
  },
  {
    id: 'application',
    name: '모집 서류',
    icon: '📋',
    desc: '서류 질이 높아질수록 더 우수한 모험가가 찾아옵니다.',
    effectLabel: (lv) => `서류 등급: ${['일반','일반','마법','마법','희귀','희귀','영웅','영웅','전설'][Math.min(lv, 8)]} 이상 출현`,
    baseCost: { gold: 1500, material: 5 },
    costMult: 1.8,
    maxLevel: 8,
  },
  {
    id: 'warehouse',
    name: '창고',
    icon: '📦',
    desc: '장비와 아이템을 보관합니다. 레벨당 보관 칸이 늘어납니다.',
    effectLabel: (lv) => `보관 칸: ${lv * 5 + 10}칸`,
    baseCost: { gold: 800, material: 4 },
    costMult: 1.5,
    maxLevel: 18,
  },
  {
    id: 'laboratory',
    name: '연구소',
    icon: '⚗️',
    desc: '경험치 책을 제작합니다. 레벨이 높을수록 더 좋은 책과 빠른 제작이 가능합니다.',
    effectLabel: (lv) => {
      const maxGrade = lv >= 8 ? '전설' : lv >= 6 ? '영웅' : lv >= 4 ? '희귀' : lv >= 2 ? '마법' : '일반';
      return `제작 속도: ${100 + lv * 10}%, 최고 책: ${maxGrade}`;
    },
    baseCost: { gold: 1200, material: 6 },
    costMult: 1.6,
    maxLevel: 12,
  },
];

// 파견 지역 정의
const AREAS = [
  // ===== 베른 왕국 (1-5) =====
  {
    id: 'forest',
    stage: 1,
    name: '베른 근교 숲',
    icon: '🌲',
    country: '베른',
    unlocked: true,
    unlockDesc: '처음부터 개방',
    maxProgress: 200,
    monsters: [
      { name: '늑대',      sprite: 'assets/monsters/animals/wolf.png',        boss: false },
      { name: '멧돼지',    sprite: 'assets/monsters/animals/hog.png',         boss: false },
      { name: '쥐',        sprite: 'assets/monsters/animals/rat.png',         boss: false },
      { name: '거대 거미', sprite: 'assets/monsters/animals/wolf_spider.png', boss: false },
      { name: '독사',      sprite: 'assets/monsters/animals/snake.png',       boss: false },
      { name: '곰 (보스)',     sprite: 'assets/monsters/animals/bear.png', boss: true },
      { name: '와르그 (보스)', sprite: 'assets/monsters/animals/warg.png', boss: true },
    ],
    goldPerSec: 5,
    materialPerMin: 1.5,
  },
  {
    id: 'mine',
    stage: 2,
    name: '베른 석재 광산',
    icon: '⛏️',
    country: '베른',
    unlocked: false,
    unlockDesc: '1단계 진행도 200 달성',
    unlockCondition: { areaId: 'forest', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '거대 딱정벌레', sprite: 'assets/monsters/animals/giant_beetle.png',    boss: false },
      { name: '거대 지네',     sprite: 'assets/monsters/animals/giant_centipede.png', boss: false },
      { name: '바위 지렁이',   sprite: 'assets/monsters/animals/rock_worm.png',       boss: false },
      { name: '거대 두꺼비',   sprite: 'assets/monsters/animals/giant_toad.png',      boss: false },
      { name: '전갈',          sprite: 'assets/monsters/animals/scorpion.png',        boss: false },
      { name: '거대 전갈 (보스)',   sprite: 'assets/monsters/animals/giant_scorpion.png', boss: true },
      { name: '암석 지렁이 (보스)', sprite: 'assets/monsters/animals/rock_worm.png',      boss: true },
    ],
    goldPerSec: 12,
    materialPerMin: 3.5,
  },
  {
    id: 'mountain',
    stage: 3,
    name: '베른 금광산',
    icon: '🪙',
    country: '베른',
    unlocked: false,
    unlockDesc: '2단계 진행도 200 달성',
    unlockCondition: { areaId: 'mine', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '광산 약탈자',   sprite: 'assets/monsters/human.png',         boss: false },
      { name: '광산 사냥개',   sprite: 'assets/monsters/animals/warg.png',  boss: false },
      { name: '동굴 그리폰',   sprite: 'assets/monsters/hippogriff.png',    boss: false },
      { name: '만티코어',      sprite: 'assets/monsters/manticore.png',     boss: false },
      { name: '동굴 와이번',   sprite: 'assets/monsters/wyvern.png',        boss: false },
      { name: '동굴의 히포그리프 (보스)', sprite: 'assets/monsters/hippogriff.png', boss: true },
      { name: '황금 미노타우르 (보스)',   sprite: 'assets/monsters/minotaur.png',   boss: true },
    ],
    goldPerSec: 12,
    materialPerMin: 3,
  },
  {
    id: 'coast',
    stage: 4,
    name: '베른 변경 평원',
    icon: '🌾',
    country: '베른',
    unlocked: false,
    unlockDesc: '3단계 진행도 200 달성',
    unlockCondition: { areaId: 'mountain', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '재칼',          sprite: 'assets/monsters/animals/jackal.png',    boss: false },
      { name: '평원 하운드',   sprite: 'assets/monsters/animals/hound.png',     boss: false },
      { name: '켄타우로스',    sprite: 'assets/monsters/centaur.png',           boss: false },
      { name: '하피',          sprite: 'assets/monsters/harpy.png',             boss: false },
      { name: '들소',          sprite: 'assets/monsters/animals/yak.png',       boss: false },
      { name: '평원의 군주 (보스)',   sprite: 'assets/monsters/cyclops.png',         boss: true },
      { name: '변경의 수호자 (보스)', sprite: 'assets/monsters/centaur_warrior.png', boss: true },
    ],
    goldPerSec: 18,
    materialPerMin: 4,
  },
  {
    id: 'etheria',
    stage: 5,
    name: '베른 국경 관문',
    icon: '🏰',
    country: '베른',
    unlocked: false,
    unlockDesc: '4단계 진행도 200 달성',
    unlockCondition: { areaId: 'coast', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '고블린',        sprite: 'assets/monsters/goblin.png',      boss: false },
      { name: '홉고블린',      sprite: 'assets/monsters/hobgoblin.png',   boss: false },
      { name: '오크 전사',     sprite: 'assets/monsters/orc_warrior.png', boss: false },
      { name: '오크 기사',     sprite: 'assets/monsters/orc_knight.png',  boss: false },
      { name: '관문 경비대',   sprite: 'assets/monsters/vault_guard.png', boss: false },
      { name: '오크 전쟁군주 (보스)', sprite: 'assets/monsters/orc_warlord.png', boss: true },
      { name: '관문 마법사 (보스)',   sprite: 'assets/monsters/wizard.png',      boss: true },
    ],
    goldPerSec: 35,
    materialPerMin: 8,
  },

  // ===== 칸 자유 도시 (6-10) =====
  {
    id: 'ordos',
    stage: 6,
    name: '칸 외곽 대장간 거리',
    icon: '🔥',
    country: '칸',
    unlocked: false,
    unlockDesc: '5단계 진행도 200 달성',
    unlockCondition: { areaId: 'etheria', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '화염 정령',     sprite: 'assets/monsters/demons/efreet.png',       boss: false },
      { name: '용광로 기사',   sprite: 'assets/monsters/hell_knight.png',         boss: false },
      { name: '대장간 수호자', sprite: 'assets/monsters/demons/executioner.png',  boss: false },
      { name: '불꽃 악마',     sprite: 'assets/monsters/demons/sun_demon.png',    boss: false },
      { name: '화염 악마',     sprite: 'assets/monsters/demons/balrug.png',       boss: false },
      { name: '화염의 군주 (보스)',     sprite: 'assets/monsters/demons/pit_fiend.png', boss: true },
      { name: '대장간의 수호신 (보스)', sprite: 'assets/monsters/demons/fiend.png',     boss: true },
    ],
    goldPerSec: 80,
    materialPerMin: 18,
  },
  {
    id: 'frostpeak',
    stage: 7,
    name: '칸 광산 깊은 곳',
    icon: '🐉',
    country: '칸',
    unlocked: false,
    unlockDesc: '6단계 진행도 200 달성',
    unlockCondition: { areaId: 'ordos', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '고대 암석 뱀',  sprite: 'assets/monsters/animals/lava_snake.png', boss: false },
      { name: '지하 용암어',   sprite: 'assets/monsters/animals/lava_fish.png',  boss: false },
      { name: '광맥 지렁이',   sprite: 'assets/monsters/animals/lava_worm.png',  boss: false },
      { name: '광산 드레이크', sprite: 'assets/monsters/fire_drake.png',         boss: false },
      { name: '고대 드래곤',   sprite: 'assets/monsters/storm_dragon.png',       boss: false },
      { name: '황금 드래곤 (보스)', sprite: 'assets/monsters/golden_dragon.png',  boss: true },
      { name: '티아마트 (보스)',    sprite: 'assets/monsters/unique/tiamat.png',  boss: true },
    ],
    goldPerSec: 200,
    materialPerMin: 45,
  },
  {
    id: 'kan_sewer',
    stage: 8,
    name: '칸 하수도 미궁',
    icon: '🌀',
    country: '칸',
    unlocked: false,
    unlockDesc: '7단계 진행도 200 달성',
    unlockCondition: { areaId: 'frostpeak', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '쥐 무리',       sprite: 'assets/monsters/animals/rat.png',          boss: false },
      { name: '코볼트',        sprite: 'assets/monsters/kobold.png',               boss: false },
      { name: '늪 지렁이',     sprite: 'assets/monsters/animals/swamp_worm.png',   boss: false },
      { name: '거대 거머리',   sprite: 'assets/monsters/animals/giant_leech.png',  boss: false },
      { name: '트롤',          sprite: 'assets/monsters/troll.png',               boss: false },
      { name: '심층 트롤 (보스)',       sprite: 'assets/monsters/deep_troll.png',              boss: true },
      { name: '코볼트 악마술사 (보스)', sprite: 'assets/monsters/kobold_demonologist.png',     boss: true },
    ],
    goldPerSec: 500,
    materialPerMin: 110,
  },
  {
    id: 'kan_port',
    stage: 9,
    name: '칸 무역항',
    icon: '⚓',
    country: '칸',
    unlocked: false,
    unlockDesc: '8단계 진행도 200 달성',
    unlockCondition: { areaId: 'kan_sewer', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '인어 전사',    sprite: 'assets/monsters/merfolk_fighter.png',    boss: false },
      { name: '인어 창병',    sprite: 'assets/monsters/merfolk_javelineer.png', boss: false },
      { name: '인어 마법사',  sprite: 'assets/monsters/merfolk_aquamancer.png', boss: false },
      { name: '세이렌',       sprite: 'assets/monsters/siren.png',              boss: false },
      { name: '인어',         sprite: 'assets/monsters/mermaid.png',            boss: false },
      { name: '인어 대창병 (보스)', sprite: 'assets/monsters/merfolk_impaler.png',      boss: true },
      { name: '크라켄 (보스)',      sprite: 'assets/monsters/animals/kraken_head.png',  boss: true },
    ],
    goldPerSec: 1200,
    materialPerMin: 250,
  },
  {
    id: 'kan_fortress',
    stage: 10,
    name: '칸 성채',
    icon: '🗡️',
    country: '칸',
    unlocked: false,
    unlockDesc: '9단계 진행도 200 달성',
    unlockCondition: { areaId: 'kan_port', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '오크 전사',     sprite: 'assets/monsters/orc_warrior.png',     boss: false },
      { name: '오크 기사',     sprite: 'assets/monsters/orc_knight.png',      boss: false },
      { name: '오크 사제',     sprite: 'assets/monsters/orc_priest.png',      boss: false },
      { name: '오그르',        sprite: 'assets/monsters/ogre.png',            boss: false },
      { name: '성채 경비대',   sprite: 'assets/monsters/vault_guard.png',     boss: false },
      { name: '쌍두 오그르 (보스)', sprite: 'assets/monsters/two_headed_ogre.png', boss: true },
      { name: '오크 마법사 (보스)', sprite: 'assets/monsters/orc_sorcerer.png',    boss: true },
    ],
    goldPerSec: 3000,
    materialPerMin: 600,
  },

  // ===== 솔 무역 연합 (11-15) =====
  {
    id: 'sol_gate',
    stage: 11,
    name: '솔 관문 도시',
    icon: '🏙️',
    country: '솔',
    unlocked: false,
    unlockDesc: '10단계 진행도 200 달성',
    unlockCondition: { areaId: 'kan_fortress', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '그놀',         sprite: 'assets/monsters/gnoll.png',            boss: false },
      { name: '반신반수',     sprite: 'assets/monsters/yaktaur.png',          boss: false },
      { name: '켄타우로스',   sprite: 'assets/monsters/centaur.png',          boss: false },
      { name: '하피',         sprite: 'assets/monsters/harpy.png',            boss: false },
      { name: '도시 용병',    sprite: 'assets/monsters/human.png',            boss: false },
      { name: '켄타우로스 전사 (보스)', sprite: 'assets/monsters/centaur_warrior.png', boss: true },
      { name: '반신반수 대장 (보스)',   sprite: 'assets/monsters/yaktaur_captain.png', boss: true },
    ],
    goldPerSec: 7500,
    materialPerMin: 1500,
  },
  {
    id: 'sol_trade',
    stage: 12,
    name: '솔 교역로',
    icon: '🐎',
    country: '솔',
    unlocked: false,
    unlockDesc: '11단계 진행도 200 달성',
    unlockCondition: { areaId: 'sol_gate', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '켄타우로스',   sprite: 'assets/monsters/centaur.png',             boss: false },
      { name: '나가',         sprite: 'assets/monsters/naga.png',                boss: false },
      { name: '킬러 비',      sprite: 'assets/monsters/animals/killer_bee.png',  boss: false },
      { name: '지옥 사냥개',  sprite: 'assets/monsters/animals/hell_hound.png',  boss: false },
      { name: '교역로 강도',  sprite: 'assets/monsters/halfling.png',            boss: false },
      { name: '대나가 (보스)',          sprite: 'assets/monsters/greater_naga.png',     boss: true },
      { name: '켄타우로스 전사 (보스)', sprite: 'assets/monsters/centaur_warrior.png',  boss: true },
    ],
    goldPerSec: 18000,
    materialPerMin: 3600,
  },
  {
    id: 'sol_desert',
    stage: 13,
    name: '솔 사막',
    icon: '🏜️',
    country: '솔',
    unlocked: false,
    unlockDesc: '12단계 진행도 200 달성',
    unlockCondition: { areaId: 'sol_trade', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '나가 전사',     sprite: 'assets/monsters/naga_warrior.png',           boss: false },
      { name: '스핑크스',      sprite: 'assets/monsters/sphinx.png',                 boss: false },
      { name: '거대 전갈',     sprite: 'assets/monsters/animals/giant_scorpion.png', boss: false },
      { name: '코모도 드래곤', sprite: 'assets/monsters/animals/komodo_dragon.png',  boss: false },
      { name: '아나콘다',      sprite: 'assets/monsters/animals/anaconda.png',       boss: false },
      { name: '나가 마법사 (보스)',   sprite: 'assets/monsters/naga_mage.png', boss: true },
      { name: '사막의 수호신 (보스)', sprite: 'assets/monsters/sphinx.png',    boss: true },
    ],
    goldPerSec: 45000,
    materialPerMin: 9000,
  },
  {
    id: 'sol_ruins',
    stage: 14,
    name: '솔 황금 유적',
    icon: '🏛️',
    country: '솔',
    unlocked: false,
    unlockDesc: '13단계 진행도 200 달성',
    unlockCondition: { areaId: 'sol_desert', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '심층 엘프 전사',   sprite: 'assets/monsters/deep_elf_fighter.png',  boss: false },
      { name: '심층 엘프 주술사', sprite: 'assets/monsters/deep_elf_conjurer.png', boss: false },
      { name: '심층 엘프 사제',   sprite: 'assets/monsters/deep_elf_priest.png',   boss: false },
      { name: '유적 수호병',      sprite: 'assets/monsters/deep_elf_soldier.png',  boss: false },
      { name: '심층 엘프 마법사', sprite: 'assets/monsters/deep_elf_mage.png',     boss: false },
      { name: '심층 엘프 기사 (보스)',  sprite: 'assets/monsters/deep_elf_knight.png',      boss: true },
      { name: '유적의 대마법사 (보스)', sprite: 'assets/monsters/deep_elf_annihilator.png', boss: true },
    ],
    goldPerSec: 110000,
    materialPerMin: 22000,
  },
  {
    id: 'sol_capital',
    stage: 15,
    name: '솔 중심 도시',
    icon: '⚔️',
    country: '솔',
    unlocked: false,
    unlockDesc: '14단계 진행도 200 달성',
    unlockCondition: { areaId: 'sol_ruins', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '심층 엘프 소환사', sprite: 'assets/monsters/deep_elf_summoner.png',      boss: false },
      { name: '심층 엘프 검투사', sprite: 'assets/monsters/deep_elf_blademaster.png',   boss: false },
      { name: '심층 엘프 궁수',   sprite: 'assets/monsters/deep_elf_master_archer.png', boss: false },
      { name: '쌍두 오그르',      sprite: 'assets/monsters/two_headed_ogre.png',        boss: false },
      { name: '도시 수비대',      sprite: 'assets/monsters/vault_guard.png',            boss: false },
      { name: '심층 엘프 대신관 (보스)', sprite: 'assets/monsters/deep_elf_high_priest.png',  boss: true },
      { name: '도시의 수호자 (보스)',    sprite: 'assets/monsters/deep_elf_demonologist.png', boss: true },
    ],
    goldPerSec: 270000,
    materialPerMin: 54000,
  },

  // ===== 교국 에테리아 (16-20) =====
  {
    id: 'eth_outskirts',
    stage: 16,
    name: '에테리아 외곽 성읍',
    icon: '✨',
    country: '에테리아',
    unlocked: false,
    unlockDesc: '15단계 진행도 200 달성',
    unlockCondition: { areaId: 'sol_capital', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '엘프 전사',         sprite: 'assets/monsters/elf.png',                 boss: false },
      { name: '심층 엘프 마법사',   sprite: 'assets/monsters/deep_elf_mage.png',       boss: false },
      { name: '심층 엘프 저주술사', sprite: 'assets/monsters/deep_elf_death_mage.png', boss: false },
      { name: '성읍 경비병',        sprite: 'assets/monsters/human.png',               boss: false },
      { name: '오염된 오크',        sprite: 'assets/monsters/deformed_orc.png',        boss: false },
      { name: '심층 엘프 기사 (보스)',    sprite: 'assets/monsters/deep_elf_knight.png',   boss: true },
      { name: '성읍의 대마법사 (보스)',   sprite: 'assets/monsters/deep_elf_sorcerer.png',  boss: true },
    ],
    goldPerSec: 680000,
    materialPerMin: 136000,
  },
  {
    id: 'eth_cathedral',
    stage: 17,
    name: '에테리아 성당 지하',
    icon: '💒',
    country: '에테리아',
    unlocked: false,
    unlockDesc: '16단계 진행도 200 달성',
    unlockCondition: { areaId: 'eth_outskirts', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '지하 망령',         sprite: 'assets/monsters/demons/shadow_demon.png',  boss: false },
      { name: '부패한 성직자',      sprite: 'assets/monsters/necromancer.png',          boss: false },
      { name: '심층 엘프 사령술사', sprite: 'assets/monsters/deep_elf_death_mage.png', boss: false },
      { name: '지하 악마',          sprite: 'assets/monsters/demons/rotting_devil.png', boss: false },
      { name: '혼돈의 생성물',      sprite: 'assets/monsters/demons/chaos_spawn.png',   boss: false },
      { name: '지하의 사신 (보스)',         sprite: 'assets/monsters/demons/reaper.png',              boss: true },
      { name: '성당 지하의 공포 (보스)',    sprite: 'assets/monsters/demons/abomination_large.png',   boss: true },
    ],
    goldPerSec: 1700000,
    materialPerMin: 340000,
  },
  {
    id: 'eth_arcane',
    stage: 18,
    name: '에테리아 마법 연구원',
    icon: '🔮',
    country: '에테리아',
    unlocked: false,
    unlockDesc: '17단계 진행도 200 달성',
    unlockCondition: { areaId: 'eth_cathedral', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '마법 연구원',        sprite: 'assets/monsters/wizard.png',                boss: false },
      { name: '심층 엘프 소환사',   sprite: 'assets/monsters/deep_elf_summoner.png',     boss: false },
      { name: '심층 엘프 악마술사', sprite: 'assets/monsters/deep_elf_demonologist.png', boss: false },
      { name: '오염된 인간',        sprite: 'assets/monsters/deformed_human.png',         boss: false },
      { name: '마법 생성물',        sprite: 'assets/monsters/giant_amoeba.png',           boss: false },
      { name: '마법 연구원장 (보스)', sprite: 'assets/monsters/deep_elf_annihilator.png', boss: true },
      { name: '소환된 악마 (보스)',  sprite: 'assets/monsters/demons/neqoxec.png',         boss: true },
    ],
    goldPerSec: 4200000,
    materialPerMin: 840000,
  },
  {
    id: 'eth_sky',
    stage: 19,
    name: '에테리아 천공 요새',
    icon: '☁️',
    country: '에테리아',
    unlocked: false,
    unlockDesc: '18단계 진행도 200 달성',
    unlockCondition: { areaId: 'eth_arcane', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '천사',          sprite: 'assets/monsters/angel.png',         boss: false },
      { name: '케럽',          sprite: 'assets/monsters/holy/cherub.png',   boss: false },
      { name: '하피',          sprite: 'assets/monsters/harpy.png',         boss: false },
      { name: '타락한 천사',   sprite: 'assets/monsters/demonspawn.png',    boss: false },
      { name: '신성 수호자',   sprite: 'assets/monsters/holy/paladin.png',  boss: false },
      { name: '천공 성기사 (보스)',   sprite: 'assets/monsters/holy/shedu.png',  boss: true },
      { name: '요새의 수호신 (보스)', sprite: 'assets/monsters/holy/ophan.png',  boss: true },
    ],
    goldPerSec: 10500000,
    materialPerMin: 2100000,
  },
  {
    id: 'eth_temple',
    stage: 20,
    name: '에테리아 대신전',
    icon: '⛩️',
    country: '에테리아',
    unlocked: false,
    unlockDesc: '19단계 진행도 200 달성',
    unlockCondition: { areaId: 'eth_sky', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '신전 수호자',   sprite: 'assets/monsters/holy/paladin.png',        boss: false },
      { name: '성전 기사',     sprite: 'assets/monsters/hell_knight.png',         boss: false },
      { name: '오판',          sprite: 'assets/monsters/holy/ophan.png',          boss: false },
      { name: '동방 용',       sprite: 'assets/monsters/holy/eastern_dragon.png', boss: false },
      { name: '쉐두',          sprite: 'assets/monsters/holy/shedu.png',          boss: false },
      { name: '신전의 주인 (보스)',   sprite: 'assets/monsters/holy/apis.png',          boss: true },
      { name: '에테리아의 성군 (보스)', sprite: 'assets/monsters/unique/saint_roka.png', boss: true },
    ],
    goldPerSec: 26000000,
    materialPerMin: 5200000,
  },

  // ===== 신성 제국 오르도스 (21-25) =====
  {
    id: 'ord_border',
    stage: 21,
    name: '오르도스 국경 초소',
    icon: '💀',
    country: '오르도스',
    unlocked: false,
    unlockDesc: '20단계 진행도 200 달성',
    unlockCondition: { areaId: 'eth_temple', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '레뮤르',        sprite: 'assets/monsters/demons/lemure.png',         boss: false },
      { name: '헬리온',        sprite: 'assets/monsters/demons/hellion.png',        boss: false },
      { name: '지옥 날개',     sprite: 'assets/monsters/demons/hellwing.png',       boss: false },
      { name: '얼음 악마',     sprite: 'assets/monsters/demons/ice_devil.png',      boss: false },
      { name: '오염된 엘프',   sprite: 'assets/monsters/deformed_elf.png',          boss: false },
      { name: '국경 수비대장 (보스)', sprite: 'assets/monsters/demons/hairy_devil.png',   boss: true },
      { name: '공포의 악령 (보스)',   sprite: 'assets/monsters/demons/unseen_horror.png', boss: true },
    ],
    goldPerSec: 65000000,
    materialPerMin: 13000000,
  },
  {
    id: 'ord_wasteland',
    stage: 22,
    name: '오르도스 황무지',
    icon: '☠️',
    country: '오르도스',
    unlocked: false,
    unlockDesc: '21단계 진행도 200 달성',
    unlockCondition: { areaId: 'ord_border', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '연기 악마',   sprite: 'assets/monsters/demons/smoke_demon.png',  boss: false },
      { name: '붉은 악마',   sprite: 'assets/monsters/demons/red_devil.png',    boss: false },
      { name: '주황 악마',   sprite: 'assets/monsters/demons/orange_demon.png', boss: false },
      { name: '얼음 마귀',   sprite: 'assets/monsters/demons/ice_fiend.png',    boss: false },
      { name: '파란 죽음',   sprite: 'assets/monsters/demons/blue_death.png',   boss: false },
      { name: '황무지의 군주 (보스)', sprite: 'assets/monsters/demons/cacodemon.png', boss: true },
      { name: '사신 (보스)',          sprite: 'assets/monsters/demons/reaper.png',    boss: true },
    ],
    goldPerSec: 160000000,
    materialPerMin: 32000000,
  },
  {
    id: 'ord_prison',
    stage: 23,
    name: '오르도스 지하 감옥',
    icon: '🔒',
    country: '오르도스',
    unlocked: false,
    unlockDesc: '22단계 진행도 200 달성',
    unlockCondition: { areaId: 'ord_wasteland', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '고문관',        sprite: 'assets/monsters/demons/tormentor.png',       boss: false },
      { name: '영혼 포식자',   sprite: 'assets/monsters/demons/soul_eater.png',      boss: false },
      { name: '공포의 존재',   sprite: 'assets/monsters/demons/ugly_thing.png',      boss: false },
      { name: '거대 공포',     sprite: 'assets/monsters/demons/very_ugly_thing.png', boss: false },
      { name: '지하 악마 거미', sprite: 'assets/monsters/demons/demonic_crawler.png', boss: false },
      { name: '지하의 처형자 (보스)', sprite: 'assets/monsters/demons/executioner.png', boss: true },
      { name: '감옥의 군주 (보스)',   sprite: 'assets/monsters/demons/fiend.png',      boss: true },
    ],
    goldPerSec: 400000000,
    materialPerMin: 80000000,
  },
  {
    id: 'ord_fortress',
    stage: 24,
    name: '오르도스 마왕성 외벽',
    icon: '👁️',
    country: '오르도스',
    unlocked: false,
    unlockDesc: '23단계 진행도 200 달성',
    unlockCondition: { areaId: 'ord_prison', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '황금 눈',        sprite: 'assets/monsters/golden_eye.png',         boss: false },
      { name: '빛나는 눈',      sprite: 'assets/monsters/shining_eye.png',        boss: false },
      { name: '배수 눈',        sprite: 'assets/monsters/eye_of_draining.png',    boss: false },
      { name: '대파괴 눈',      sprite: 'assets/monsters/eye_of_devastation.png', boss: false },
      { name: '마왕성 경비 악마', sprite: 'assets/monsters/demons/shadow_fiend.png', boss: false },
      { name: '눈의 군주 (보스)',        sprite: 'assets/monsters/great_orb_of_eyes.png', boss: true },
      { name: '마왕성의 수문장 (보스)',  sprite: 'assets/monsters/demons/pit_fiend.png',  boss: true },
    ],
    goldPerSec: 1000000000,
    materialPerMin: 200000000,
  },
  {
    id: 'ord_depths',
    stage: 25,
    name: '오르도스 마왕성 심부',
    icon: '🏯',
    country: '오르도스',
    unlocked: false,
    unlockDesc: '24단계 진행도 200 달성',
    unlockCondition: { areaId: 'ord_fortress', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '지옥의 군주',   sprite: 'assets/monsters/demons/balrug.png',               boss: false },
      { name: '혼돈의 괴물',   sprite: 'assets/monsters/demons/tentacled_monstrosity.png', boss: false },
      { name: '다에바',        sprite: 'assets/monsters/daeva.png',                        boss: false },
      { name: '라크샤사',      sprite: 'assets/monsters/demons/rakshasa.png',              boss: false },
      { name: '마왕성 수호자', sprite: 'assets/monsters/orb_guardian.png',                boss: false },
      { name: '아스모데우스 (보스)', sprite: 'assets/monsters/unique/asmodeus.png', boss: true },
      { name: '디스페이터 (보스)',   sprite: 'assets/monsters/unique/dispater.png', boss: true },
    ],
    goldPerSec: 2500000000,
    materialPerMin: 500000000,
  },

  // ===== 아이언피스트 공국 (26-30) =====
  {
    id: 'ip_mine',
    stage: 26,
    name: '아이언피스트 광산 지구',
    icon: '⛏️',
    country: '아이언피스트',
    unlocked: false,
    unlockDesc: '25단계 진행도 200 달성',
    unlockCondition: { areaId: 'ord_depths', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '드워프',       sprite: 'assets/monsters/dwarf.png',            boss: false },
      { name: '바위 트롤',    sprite: 'assets/monsters/rock_troll.png',       boss: false },
      { name: '철제 트롤',    sprite: 'assets/monsters/iron_troll.png',       boss: false },
      { name: '광산 거인',    sprite: 'assets/monsters/hill_giant.png',       boss: false },
      { name: '철제 악마',    sprite: 'assets/monsters/demons/iron_devil.png', boss: false },
      { name: '깊은 트롤 (보스)',   sprite: 'assets/monsters/deep_troll.png',  boss: true },
      { name: '광산 거인왕 (보스)', sprite: 'assets/monsters/ettin.png',       boss: true },
    ],
    goldPerSec: 6250000000,
    materialPerMin: 1250000000,
  },
  {
    id: 'ip_plains',
    stage: 27,
    name: '아이언피스트 강철 벌판',
    icon: '🛡️',
    country: '아이언피스트',
    unlocked: false,
    unlockDesc: '26단계 진행도 200 달성',
    unlockCondition: { areaId: 'ip_mine', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '언덕 거인',    sprite: 'assets/monsters/hill_giant.png',   boss: false },
      { name: '돌 거인',      sprite: 'assets/monsters/stone_giant.png',  boss: false },
      { name: '불의 거인',    sprite: 'assets/monsters/fire_giant.png',   boss: false },
      { name: '서리 거인',    sprite: 'assets/monsters/frost_giant.png',  boss: false },
      { name: '사이클롭스',   sprite: 'assets/monsters/cyclops.png',      boss: false },
      { name: '거인 군주 (보스)',  sprite: 'assets/monsters/titan.png',                boss: true },
      { name: '폴리페무스 (보스)', sprite: 'assets/monsters/unique/polyphemus.png',    boss: true },
    ],
    goldPerSec: 15600000000,
    materialPerMin: 3120000000,
  },
  {
    id: 'ip_fortress',
    stage: 28,
    name: '아이언피스트 철갑 요새',
    icon: '🔧',
    country: '아이언피스트',
    unlocked: false,
    unlockDesc: '27단계 진행도 200 달성',
    unlockCondition: { areaId: 'ip_plains', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '철 드래곤',       sprite: 'assets/monsters/iron_dragon.png',  boss: false },
      { name: '증기 드래곤',     sprite: 'assets/monsters/steam_dragon.png', boss: false },
      { name: '철제 트롤',       sprite: 'assets/monsters/iron_troll.png',   boss: false },
      { name: '요새 경비 거인',  sprite: 'assets/monsters/stone_giant.png',  boss: false },
      { name: '철갑 드레이크',   sprite: 'assets/monsters/death_drake.png',  boss: false },
      { name: '불의 거인왕 (보스)',        sprite: 'assets/monsters/fire_giant.png',       boss: true },
      { name: '철갑 요새의 수호자 (보스)', sprite: 'assets/monsters/unique/antaeus.png',   boss: true },
    ],
    goldPerSec: 39000000000,
    materialPerMin: 7800000000,
  },
  {
    id: 'ip_underground',
    stage: 29,
    name: '아이언피스트 기계 지하도시',
    icon: '⚙️',
    country: '아이언피스트',
    unlocked: false,
    unlockDesc: '28단계 진행도 200 달성',
    unlockCondition: { areaId: 'ip_fortress', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '철 악마',       sprite: 'assets/monsters/demons/iron_devil.png', boss: false },
      { name: '철제 골렘',     sprite: 'assets/monsters/iron_troll.png',        boss: false },
      { name: '거대 눈알',     sprite: 'assets/monsters/giant_eyeball.png',     boss: false },
      { name: '지하도시 거인', sprite: 'assets/monsters/hill_giant.png',        boss: false },
      { name: '기계 수호자',   sprite: 'assets/monsters/orb_guardian.png',      boss: false },
      { name: '지하도시 군주 (보스)', sprite: 'assets/monsters/titan.png',              boss: true },
      { name: '기계 신 (보스)',       sprite: 'assets/monsters/unique/cerebov.png',     boss: true },
    ],
    goldPerSec: 97500000000,
    materialPerMin: 19500000000,
  },
  {
    id: 'ip_throne',
    stage: 30,
    name: '아이언피스트 절대 요새',
    icon: '🗡️',
    country: '아이언피스트',
    unlocked: false,
    unlockDesc: '29단계 진행도 200 달성',
    unlockCondition: { areaId: 'ip_underground', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '타이탄',         sprite: 'assets/monsters/titan.png',              boss: false },
      { name: '철의 수호자',   sprite: 'assets/monsters/iron_dragon.png',         boss: false },
      { name: '강철 악마',     sprite: 'assets/monsters/demons/iron_devil.png',   boss: false },
      { name: '요새 정예 부대', sprite: 'assets/monsters/vault_guard.png',        boss: false },
      { name: '서리 거인 정예', sprite: 'assets/monsters/frost_giant.png',        boss: false },
      { name: '서리 거인왕 (보스)',        sprite: 'assets/monsters/unique/antaeus.png',      boss: true },
      { name: '절대 요새의 지배자 (보스)', sprite: 'assets/monsters/unique/gloorx_vloq.png',  boss: true },
    ],
    goldPerSec: 243750000000,
    materialPerMin: 48750000000,
  },

  // ===== 드래곤 왕국 (31-35) =====
  {
    id: 'dk_border',
    stage: 31,
    name: '드래곤 왕국 변경',
    icon: '🐲',
    country: '드래곤 왕국',
    unlocked: false,
    unlockDesc: '30단계 진행도 200 달성',
    unlockCondition: { areaId: 'ip_throne', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '린드웜',        sprite: 'assets/monsters/lindwurm.png',      boss: false },
      { name: '늪 드레이크',   sprite: 'assets/monsters/swamp_drake.png',   boss: false },
      { name: '얼룩 드래곤',   sprite: 'assets/monsters/mottled_dragon.png', boss: false },
      { name: '늪 드래곤',     sprite: 'assets/monsters/swamp_dragon.png',  boss: false },
      { name: '죽음 드레이크', sprite: 'assets/monsters/death_drake.png',   boss: false },
      { name: '변경 드래곤 군주 (보스)', sprite: 'assets/monsters/dragon.png',      boss: true },
      { name: '드래곤 왕국 선봉 (보스)', sprite: 'assets/monsters/fire_drake.png',  boss: true },
    ],
    goldPerSec: 610000000000,
    materialPerMin: 122000000000,
  },
  {
    id: 'dk_volcano',
    stage: 32,
    name: '드래곤 왕국 화산지대',
    icon: '🌋',
    country: '드래곤 왕국',
    unlocked: false,
    unlockDesc: '31단계 진행도 200 달성',
    unlockCondition: { areaId: 'dk_border', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '화염 드레이크',   sprite: 'assets/monsters/fire_drake.png',          boss: false },
      { name: '용암 뱀',         sprite: 'assets/monsters/animals/lava_snake.png',  boss: false },
      { name: '용암 지렁이',     sprite: 'assets/monsters/animals/lava_worm.png',   boss: false },
      { name: '화산 드래곤',     sprite: 'assets/monsters/mottled_dragon.png',      boss: false },
      { name: '불의 거인',       sprite: 'assets/monsters/fire_giant.png',          boss: false },
      { name: '화산의 수호자 (보스)', sprite: 'assets/monsters/storm_dragon.png',   boss: true },
      { name: '화염 군주 (보스)',     sprite: 'assets/monsters/unique/azrael.png',  boss: true },
    ],
    goldPerSec: 1525000000000,
    materialPerMin: 305000000000,
  },
  {
    id: 'dk_lair',
    stage: 33,
    name: '드래곤 왕국 고룡 서식지',
    icon: '🐉',
    country: '드래곤 왕국',
    unlocked: false,
    unlockDesc: '32단계 진행도 200 달성',
    unlockCondition: { areaId: 'dk_volcano', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '그림자 드래곤', sprite: 'assets/monsters/shadow_dragon.png',      boss: false },
      { name: '얼음 드래곤',   sprite: 'assets/monsters/ice_dragon.png',         boss: false },
      { name: '수은 드래곤',   sprite: 'assets/monsters/quicksilver_dragon.png', boss: false },
      { name: '철 드래곤',     sprite: 'assets/monsters/iron_dragon.png',        boss: false },
      { name: '고룡 수호자',   sprite: 'assets/monsters/golden_dragon.png',      boss: false },
      { name: '고대 드래곤 군주 (보스)', sprite: 'assets/monsters/storm_dragon.png',      boss: true },
      { name: '크타후아 (보스)',         sprite: 'assets/monsters/unique/xtahua.png',      boss: true },
    ],
    goldPerSec: 3800000000000,
    materialPerMin: 760000000000,
  },
  {
    id: 'dk_realm',
    stage: 34,
    name: '드래곤 왕국 용왕의 영역',
    icon: '👑',
    country: '드래곤 왕국',
    unlocked: false,
    unlockDesc: '33단계 진행도 200 달성',
    unlockCondition: { areaId: 'dk_lair', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '황금 드래곤',       sprite: 'assets/monsters/golden_dragon.png',      boss: false },
      { name: '폭풍 드래곤',       sprite: 'assets/monsters/storm_dragon.png',       boss: false },
      { name: '용왕의 근위대',     sprite: 'assets/monsters/quicksilver_dragon.png', boss: false },
      { name: '고대 화룡',         sprite: 'assets/monsters/fire_drake.png',         boss: false },
      { name: '드래곤 정예 수호자', sprite: 'assets/monsters/iron_dragon.png',       boss: false },
      { name: '드래곤 왕 (보스)', sprite: 'assets/monsters/golden_dragon.png',       boss: true },
      { name: '티아마트 (보스)',  sprite: 'assets/monsters/unique/tiamat.png',        boss: true },
    ],
    goldPerSec: 9500000000000,
    materialPerMin: 1900000000000,
  },
  {
    id: 'dk_throne',
    stage: 35,
    name: '드래곤 왕국 용왕의 좌',
    icon: '🔱',
    country: '드래곤 왕국',
    unlocked: false,
    unlockDesc: '34단계 진행도 200 달성',
    unlockCondition: { areaId: 'dk_realm', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '용왕의 첫째 용',   sprite: 'assets/monsters/golden_dragon.png',   boss: false },
      { name: '용왕의 둘째 용',   sprite: 'assets/monsters/storm_dragon.png',    boss: false },
      { name: '용왕의 셋째 용',   sprite: 'assets/monsters/shadow_dragon.png',   boss: false },
      { name: '용왕의 넷째 용',   sprite: 'assets/monsters/ice_dragon.png',      boss: false },
      { name: '용왕의 최강 근위', sprite: 'assets/monsters/quicksilver_dragon.png', boss: false },
      { name: '전설의 용왕 (보스)',  sprite: 'assets/monsters/unique/tiamat.png',              boss: true },
      { name: '지옥의 뱀 (보스)',    sprite: 'assets/monsters/unique/serpent_of_hell.png',     boss: true },
    ],
    goldPerSec: 23750000000000,
    materialPerMin: 4750000000000,
  },

  // ===== 미지의 영역 (36-40) =====
  {
    id: 'beyond_gate',
    stage: 36,
    name: '심연의 관문',
    icon: '🌑',
    country: '미지의 영역',
    unlocked: false,
    unlockDesc: '35단계 진행도 200 달성',
    unlockCondition: { areaId: 'dk_throne', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '심연의 공포',   sprite: 'assets/monsters/demons/unseen_horror.png',         boss: false },
      { name: '촉수 괴물',     sprite: 'assets/monsters/demons/tentacled_monstrosity.png', boss: false },
      { name: '혼돈 생성물',   sprite: 'assets/monsters/demons/chaos_spawn.png',           boss: false },
      { name: '심연 수호자',   sprite: 'assets/monsters/orb_guardian.png',                boss: false },
      { name: '시공 악마',     sprite: 'assets/monsters/demons/neqoxec.png',              boss: false },
      { name: '심연의 군주 (보스)', sprite: 'assets/monsters/demons/abomination_large.png', boss: true },
      { name: '에레쉬키갈 (보스)',  sprite: 'assets/monsters/unique/ereshkigal.png',        boss: true },
    ],
    goldPerSec: 59375000000000,
    materialPerMin: 11875000000000,
  },
  {
    id: 'beyond_chaos',
    stage: 37,
    name: '혼돈의 공간',
    icon: '🌀',
    country: '미지의 영역',
    unlocked: false,
    unlockDesc: '36단계 진행도 200 달성',
    unlockCondition: { areaId: 'beyond_gate', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '변신자',          sprite: 'assets/monsters/shapeshifter.png',         boss: false },
      { name: '빛나는 변신자',   sprite: 'assets/monsters/glowing_shapeshifter.png', boss: false },
      { name: '혼돈의 생성물',   sprite: 'assets/monsters/demons/chaos_spawn.png',   boss: false },
      { name: '거대 아메바',     sprite: 'assets/monsters/giant_amoeba.png',         boss: false },
      { name: '고동치는 덩어리', sprite: 'assets/monsters/pulsating_lump.png',       boss: false },
      { name: '혼돈의 지배자 (보스)', sprite: 'assets/monsters/demons/very_ugly_thing.png', boss: true },
      { name: '므놀레그 (보스)',       sprite: 'assets/monsters/unique/mnoleg.png',          boss: true },
    ],
    goldPerSec: 148437500000000,
    materialPerMin: 29687500000000,
  },
  {
    id: 'beyond_divine',
    stage: 38,
    name: '신들의 전장',
    icon: '⚡',
    country: '미지의 영역',
    unlocked: false,
    unlockDesc: '37단계 진행도 200 달성',
    unlockCondition: { areaId: 'beyond_chaos', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '타락한 천사',   sprite: 'assets/monsters/demonspawn.png',        boss: false },
      { name: '전장의 천사',   sprite: 'assets/monsters/angel.png',             boss: false },
      { name: '전장의 악마',   sprite: 'assets/monsters/demons/balrug.png',     boss: false },
      { name: '신성 수호자',   sprite: 'assets/monsters/holy/ophan.png',        boss: false },
      { name: '신들의 전령',   sprite: 'assets/monsters/daeva.png',             boss: false },
      { name: '전장의 신 (보스)', sprite: 'assets/monsters/unique/lom_lobon.png', boss: true },
      { name: '게리온 (보스)',    sprite: 'assets/monsters/unique/geryon.png',    boss: true },
    ],
    goldPerSec: 371093750000000,
    materialPerMin: 74218750000000,
  },
  {
    id: 'beyond_end',
    stage: 39,
    name: '세계의 끝',
    icon: '🌌',
    country: '미지의 영역',
    unlocked: false,
    unlockDesc: '38단계 진행도 200 달성',
    unlockCondition: { areaId: 'beyond_divine', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '세계의 끝 수호자', sprite: 'assets/monsters/orb_guardian.png',              boss: false },
      { name: '거대 오렌지 뇌',   sprite: 'assets/monsters/giant_orange_brain.png',        boss: false },
      { name: '파괴의 눈',        sprite: 'assets/monsters/eye_of_devastation.png',        boss: false },
      { name: '궁극의 악령',      sprite: 'assets/monsters/demons/abomination_large.png',  boss: false },
      { name: '세계 끝의 악마',   sprite: 'assets/monsters/demons/tentacled_monstrosity.png', boss: false },
      { name: '세계의 끝 지배자 (보스)', sprite: 'assets/monsters/unique/gloorx_vloq.png', boss: true },
      { name: '케레보프 (보스)',         sprite: 'assets/monsters/unique/cerebov.png',      boss: true },
    ],
    goldPerSec: 927734375000000,
    materialPerMin: 185546875000000,
  },
  {
    id: 'beyond_transcend',
    stage: 40,
    name: '초월의 경지',
    icon: '∞',
    country: '미지의 영역',
    unlocked: false,
    unlockDesc: '39단계 진행도 200 달성',
    unlockCondition: { areaId: 'beyond_end', progress: 200 },
    maxProgress: 200,
    monsters: [
      { name: '초월의 악마',   sprite: 'assets/monsters/demons/abomination_large.png', boss: false },
      { name: '초월의 수호자', sprite: 'assets/monsters/orb_guardian.png',             boss: false },
      { name: '시공의 균열',   sprite: 'assets/monsters/glowing_shapeshifter.png',     boss: false },
      { name: '존재의 끝',     sprite: 'assets/monsters/pulsating_lump.png',           boss: false },
      { name: '초월의 파수꾼', sprite: 'assets/monsters/giant_orange_brain.png',       boss: false },
      { name: '초월의 신 (보스)',      sprite: 'assets/monsters/unique/mnoleg.png',     boss: true },
      { name: '세계의 어머니 (보스)', sprite: 'assets/monsters/unique/ereshkigal.png', boss: true },
    ],
    goldPerSec: 2319335937500000,
    materialPerMin: 463867187500000,
  },
];

// ===== 장비 템플릿 =====
// weapon은 branch(warrior/rogue/mage)별로 구분, armor/accessory는 공용
const EQUIPMENT_TEMPLATES = {
  weapon: {
    warrior: {
      names: { '일반': '낡은 검', '마법': '강철 검', '희귀': '은빛 검', '영웅': '성검', '전설': '전설의 검', '신화': '신화의 검' },
      icons: { '일반': 'assets/items/W_Sword001.png', '마법': 'assets/items/W_Sword003.png',
               '희귀': 'assets/items/W_Sword006.png', '영웅': 'assets/items/W_Sword009.png',
               '전설': 'assets/items/W_Sword013.png', '신화': 'assets/items/W_Sword016.png' },
      stats: { '일반': { atk: 8 }, '마법': { atk: 18 }, '희귀': { atk: 40 }, '영웅': { atk: 80 }, '전설': { atk: 160 }, '신화': { atk: 320 } },
    },
    rogue: {
      names: { '일반': '낡은 단검', '마법': '강철 단검', '희귀': '은빛 단검', '영웅': '암살자의 단검', '전설': '전설의 단검', '신화': '신화의 단검' },
      icons: { '일반': 'assets/items/W_Dagger001.png', '마법': 'assets/items/W_Dagger003.png',
               '희귀': 'assets/items/W_Dagger007.png', '영웅': 'assets/items/W_Dagger010.png',
               '전설': 'assets/items/W_Dagger014.png', '신화': 'assets/items/W_Dagger018.png' },
      stats: { '일반': { atk: 8 }, '마법': { atk: 18 }, '희귀': { atk: 40 }, '영웅': { atk: 80 }, '전설': { atk: 160 }, '신화': { atk: 320 } },
    },
    mage: {
      names: { '일반': '낡은 지팡이', '마법': '마법 지팡이', '희귀': '현자의 지팡이', '영웅': '대마법사 지팡이', '전설': '전설의 지팡이', '신화': '신화의 지팡이' },
      icons: { '일반': 'assets/items/W_Staff01.png', '마법': 'assets/items/W_Staff02.png',
               '희귀': 'assets/items/W_Staff04.png', '영웅': 'assets/items/W_Staff05.png',
               '전설': 'assets/items/W_Staff07.png', '신화': 'assets/items/W_Staff08.png' },
      stats: { '일반': { atk: 8 }, '마법': { atk: 18 }, '희귀': { atk: 40 }, '영웅': { atk: 80 }, '전설': { atk: 160 }, '신화': { atk: 320 } },
    },
  },
  armor: {
    names: { '일반': '낡은 갑옷', '마법': '강철 갑옷', '희귀': '미스릴 갑옷', '영웅': '성기사 갑옷', '전설': '전설의 갑옷', '신화': '신화의 갑옷'  },
    icons: { '일반': 'assets/items/A_Clothing01.png', '마법': 'assets/items/A_Armour01.png',
             '희귀': 'assets/items/A_Armour02.png',   '영웅': 'assets/items/A_Armour03.png',
             '전설': 'assets/items/A_Armor05.png',    '신화': 'assets/items/A_Armor04.png' },
    stats: { '일반': { hp: 30, def: 5 }, '마법': { hp: 70, def: 12 }, '희귀': { hp: 150, def: 25 },
             '영웅': { hp: 300, def: 50 }, '전설': { hp: 600, def: 100 }, '신화': { hp: 1200, def: 200 } },
  },
  accessory: {
    names: { '일반': '낡은 반지', '마법': '은 목걸이', '희귀': '마법 반지', '영웅': '성기사 훈장', '전설': '전설의 보석', '신화': '신화의 유물'  },
    icons: { '일반': 'assets/items/Ac_Necklace01.png', '마법': 'assets/items/Ac_Ring01.png',
             '희귀': 'assets/items/Ac_Necklace03.png',  '영웅': 'assets/items/Ac_Medal02.png',
             '전설': 'assets/items/Ac_Ring02.png',      '신화': 'assets/items/Ac_Medal03.png' },
    stats: { '일반': { spd: 3, crit: 3 }, '마법': { spd: 6, crit: 6 }, '희귀': { spd: 12, crit: 10 },
             '영웅': { spd: 25, crit: 15 }, '전설': { spd: 50, crit: 25 }, '신화': { spd: 80, crit: 40 } },
  },
};

// ===== 장비 추가 옵션 풀 =====
const GRADE_IDX   = { '일반': 0, '마법': 1, '희귀': 2, '영웅': 3, '전설': 4, '신화': 5 };
const OPTION_COUNT = { '일반': 0, '마법': 1, '희귀': 1, '영웅': 2, '전설': 3, '신화': 4 };

// 무기 옵션은 계열(branch)별로 구분
const _W_COMMON = [
  { id: 'w_crit_rate',  name: '치명타 확률',   type: 'stat',     stat: 'crit',    values: [3,4,6,9,13,18],    desc: v => `치명타 +${v}%` },
  { id: 'w_crit_dmg',  name: '치명타 데미지', type: 'stat',     stat: 'critDmg', values: [10,15,22,32,45,65], desc: v => `치명타 배율 +${v}%` },
  { id: 'w_atk_pct',   name: '공격력 강화',   type: 'stat_pct', stat: 'atk',     values: [5,7,10,15,22,32],   desc: v => `공격력 +${v}%` },
  { id: 'w_first_crit',name: '선제 치명타',   type: 'battle',   effect: 'firstStrikeCrit', values: [1,1,1,1,1,1], desc: () => `첫 공격 치명타 확정` },
  { id: 'w_def_break', name: '방어 감소',     type: 'battle',   effect: 'defBreak',        values: [20,25,30,40,50,65], desc: v => `방어 감소 ${v}%` },
  { id: 'w_all_pct',   name: '전능력치 강화', type: 'stat_pct', stat: 'all',     values: [2,3,5,7,10,15],    desc: v => `전능력치 +${v}%` },
];

const EQUIPMENT_OPTIONS = {
  weapon: {
    warrior: [
      ..._W_COMMON,
      { id: 'w_armor_pierce', name: '방어력 무시',    type: 'battle', effect: 'armorPierce',  values: [10,15,20,30,42,60], desc: v => `방어 무시 ${v}%` },
      { id: 'w_bleed',        name: '출혈',            type: 'battle', effect: 'bleed',        values: [15,20,25,32,40,55], desc: v => `출혈 부여 ${v}%` },
      { id: 'w_double_atk',   name: '연속 공격',      type: 'battle', effect: 'doubleAttack', values: [10,12,16,22,30,42], desc: v => `연속공격 ${v}%` },
      { id: 'w_hp_scale',     name: '체력 비례 피해', type: 'battle', effect: 'hpScaleDmg',   values: [3,4,6,9,13,18],    desc: v => `HP비례 추가피해 +${v}%` },
    ],
    rogue: [
      ..._W_COMMON,
      { id: 'w_armor_pierce', name: '방어력 무시',    type: 'battle', effect: 'armorPierce',  values: [10,15,20,30,42,60], desc: v => `방어 무시 ${v}%` },
      { id: 'w_bleed',        name: '출혈',            type: 'battle', effect: 'bleed',        values: [15,20,25,32,40,55], desc: v => `출혈 부여 ${v}%` },
      { id: 'w_double_atk',   name: '연속 공격',      type: 'battle', effect: 'doubleAttack', values: [10,12,16,22,30,42], desc: v => `연속공격 ${v}%` },
      { id: 'w_hp_scale',     name: '체력 비례 피해', type: 'battle', effect: 'hpScaleDmg',   values: [3,4,6,9,13,18],    desc: v => `HP비례 추가피해 +${v}%` },
    ],
    mage: [
      ..._W_COMMON,
      { id: 'w_spd',      name: '시전 속도',     type: 'stat',     stat: 'spd',     values: [2,4,6,9,13,18],    desc: v => `속도 +${v}` },
      { id: 'w_hp_pct',   name: '마력 체력',     type: 'stat_pct', stat: 'hp',      values: [4,6,9,13,18,26],   desc: v => `체력 +${v}%` },
      { id: 'w_crit_spd', name: '치명 시전',     type: 'stat',     stat: 'crit',    values: [5,7,10,14,20,28],  desc: v => `치명타 +${v}%` },
      { id: 'w_mag_pen',  name: '마법 관통',     type: 'battle',   effect: 'armorPierce', values: [15,20,28,38,50,65], desc: v => `방어 무시 ${v}%` },
    ],
  },
  armor: [
    { id: 'a_dmg_reduce',  name: '피해 감소',    type: 'battle',     effect: 'damageReduction', values: [5,7,10,14,20,28],    desc: v => `피해 감소 ${v}%` },
    { id: 'a_hp_pct',      name: '체력 강화',    type: 'stat_pct',   stat: 'hp',                values: [8,12,17,24,35,50],   desc: v => `체력 +${v}%` },
    { id: 'a_crit_resist', name: '치명타 저항',  type: 'battle',     effect: 'critResist',      values: [10,15,20,30,42,58],  desc: v => `치명타 피해 감소 ${v}%` },
    { id: 'a_def_pct',     name: '방어력 강화',  type: 'stat_pct',   stat: 'def',               values: [8,12,17,24,35,50],   desc: v => `방어력 +${v}%` },
    { id: 'a_shield',      name: '전투 보호막',  type: 'battle',     effect: 'startShield',     values: [30,50,80,130,200,320], desc: v => `전투보호막 ${v}` },
    { id: 'a_spd',         name: '속도 강화',    type: 'stat',       stat: 'spd',               values: [2,4,6,9,13,18],      desc: v => `속도 +${v}` },
    { id: 'a_low_hp',      name: '위기 방어',    type: 'battle',     effect: 'lowHpDmgReduce',  values: [10,15,20,28,38,52],  desc: v => `HP 40% 이하 피해 감소 +${v}%` },
    { id: 'a_def_to_hp',   name: '철벽 체력',    type: 'stat_scale', scale: 'def_to_hp',        values: [2,3,4,6,8,12],       desc: v => `방어력×${v} HP 추가` },
    { id: 'a_evasion',     name: '회피율',       type: 'battle',     effect: 'evasion',         values: [5,7,10,14,20,28],    desc: v => `회피 ${v}%` },
    { id: 'a_hp_to_def',   name: '체력 방어',    type: 'stat_scale', scale: 'hp_to_def',        values: [1,2,2,3,4,6],        desc: v => `HP/100×${v} 방어력` },
  ],
  accessory: [
    { id: 'ac_spd',        name: '속도 강화',      type: 'stat',     stat: 'spd',               values: [3,5,7,10,15,22],     desc: v => `속도 +${v}` },
    { id: 'ac_atk_pct',    name: '공격력 강화',    type: 'stat_pct', stat: 'atk',               values: [5,7,10,15,22,32],    desc: v => `공격력 +${v}%` },
    { id: 'ac_def_pct',    name: '방어력 강화',    type: 'stat_pct', stat: 'def',               values: [5,7,10,15,22,32],    desc: v => `방어력 +${v}%` },
    { id: 'ac_hp_pct',     name: '체력 강화',      type: 'stat_pct', stat: 'hp',                values: [5,7,10,15,22,32],    desc: v => `체력 +${v}%` },
    { id: 'ac_crit',       name: '치명타 확률',    type: 'stat',     stat: 'crit',              values: [3,5,7,10,15,22],     desc: v => `치명타 +${v}%` },
    { id: 'ac_dmg_reduce', name: '피해 감소',      type: 'battle',   effect: 'damageReduction', values: [3,5,7,10,15,22],     desc: v => `피해 감소 ${v}%` },
    { id: 'ac_gold',       name: '재화 획득 증가', type: 'dispatch', dispatchEffect: 'goldBonus',     values: [5,8,12,18,25,40],  desc: v => `골드 +${v}%` },
    { id: 'ac_material',   name: '재료 획득 증가', type: 'dispatch', dispatchEffect: 'materialBonus', values: [5,8,12,18,25,40],  desc: v => `재료 +${v}%` },
    { id: 'ac_crit_dmg',   name: '치명타 데미지',  type: 'stat',     stat: 'critDmg',           values: [10,15,22,32,45,65],  desc: v => `치명타 배율 +${v}%` },
    { id: 'ac_heal',       name: '전투 후 회복',   type: 'battle',   effect: 'healAfterBattle', values: [5,8,10,15,20,30],    desc: v => `전투 후 HP ${v}% 회복` },
    { id: 'ac_all',        name: '전능력치 강화',  type: 'stat_pct', stat: 'all',               values: [3,4,6,8,12,18],      desc: v => `전능력치 +${v}%` },
  ],
};

function generateEquipment(slot, grade, branch = null) {
  let tmpl;
  let jobClass = null;

  if (slot === 'weapon') {
    const branches = ['warrior', 'rogue', 'mage'];
    jobClass = branch || branches[Math.floor(Math.random() * branches.length)];
    tmpl = EQUIPMENT_TEMPLATES.weapon[jobClass];
  } else {
    tmpl = EQUIPMENT_TEMPLATES[slot];
  }

  const gIdx  = GRADE_IDX[grade];
  const count = OPTION_COUNT[grade];

  const optPool = slot === 'weapon' ? EQUIPMENT_OPTIONS.weapon[jobClass] : EQUIPMENT_OPTIONS[slot];
  const pool    = [...optPool].sort(() => Math.random() - 0.5);
  const options = pool.slice(0, count).map(opt => ({
    id:             opt.id,
    name:           opt.name,
    type:           opt.type,
    stat:           opt.stat,
    scale:          opt.scale,
    effect:         opt.effect,
    dispatchEffect: opt.dispatchEffect,
    value:          opt.values[gIdx],
    display:        opt.desc(opt.values[gIdx]),
  }));

  return {
    id:       `eq_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    name:     tmpl.names[grade],
    slot,
    grade,
    icon:     tmpl.icons[grade],
    stats:    { ...tmpl.stats[grade] },
    options,
    jobClass, // weapon만 설정 (null = 공용)
  };
}

// 상점 아이템 정의
const SHOP_ITEMS = [
  {
    id: 'exp_book_d',
    name: '경험치 서 [일반]',
    icon: 'assets/items/I_Book.png',
    desc: '모험가에게 사용하면 경험치 500 획득',
    price: 300,
    type: 'exp_book',
    expValue: 500,
  },
  {
    id: 'exp_book_c',
    name: '경험치 서 [마법]',
    icon: 'assets/items/I_Book.png',
    desc: '모험가에게 사용하면 경험치 2,000 획득',
    price: 1000,
    type: 'exp_book',
    expValue: 2000,
  },
  {
    id: 'exp_book_b',
    name: '경험치 서 [희귀]',
    icon: 'assets/items/I_Book.png',
    desc: '모험가에게 사용하면 경험치 7,000 획득',
    price: 3500,
    type: 'exp_book',
    expValue: 7000,
  },
  {
    id: 'material_d',
    name: '재료',
    icon: 'assets/items/I_Crystal01.png',
    desc: '건물 업그레이드 및 제작에 사용',
    price: 100,
    type: 'material',
    grade: '일반',
    amount: 1,
  },
  {
    id: 'shop_weapon_warrior',
    name: '낡은 검 (전사용)',
    icon: 'assets/items/W_Sword001.png',
    desc: '공격력 +8. 전사 계열 전용 무기.',
    price: 800,
    type: 'equipment',
    slot: 'weapon',
    grade: '일반',
    branch: 'warrior',
  },
  {
    id: 'shop_weapon_rogue',
    name: '낡은 단검 (도적용)',
    icon: 'assets/items/W_Dagger001.png',
    desc: '공격력 +8. 도적 계열 전용 무기.',
    price: 800,
    type: 'equipment',
    slot: 'weapon',
    grade: '일반',
    branch: 'rogue',
  },
  {
    id: 'shop_weapon_mage',
    name: '낡은 지팡이 (마법사용)',
    icon: 'assets/items/W_Staff01.png',
    desc: '공격력 +8. 마법사 계열 전용 무기.',
    price: 800,
    type: 'equipment',
    slot: 'weapon',
    grade: '일반',
    branch: 'mage',
  },
  {
    id: 'shop_armor_d',
    name: '낡은 갑옷 (일반)',
    icon: 'assets/items/A_Clothing01.png',
    desc: 'HP +30, 방어력 +5. 방어구 슬롯에 장착.',
    price: 600,
    type: 'equipment',
    slot: 'armor',
    grade: '일반',
  },
  {
    id: 'shop_accessory_d',
    name: '낡은 반지 (일반)',
    icon: 'assets/items/Ac_Necklace01.png',
    desc: '속도 +3, 치명타 +3%. 악세서리 슬롯에 장착.',
    price: 500,
    type: 'equipment',
    slot: 'accessory',
    grade: '일반',
  },
];

// ===== 리빌딩(프레스티지) 시스템 =====

// 리빌딩 조건 (all must be true)
const REBUILD_CONDITIONS = [
  { label: '베른 근교 숲 (1단계) 진행도 200 달성',   check: () => (State.areaProgress['forest']   || 0) >= 200 },
  { label: '베른 석재 광산 (2단계) 진행도 200 달성',  check: () => (State.areaProgress['mine']     || 0) >= 200 },
  { label: '베른 금광산 (3단계) 진행도 200 달성',     check: () => (State.areaProgress['mountain'] || 0) >= 200 },
  { label: '베른 변경 평원 (4단계) 진행도 200 달성',  check: () => (State.areaProgress['coast']    || 0) >= 200 },
  { label: '베른 국경 관문 (5단계) 진행도 200 달성',  check: () => (State.areaProgress['etheria']  || 0) >= 200 },
  { label: '지휘 본부 Lv.5 이상',                    check: () => (State.buildings?.headquarters  || 1) >= 5  },
];

// 프레스티지 트리 노드 정의
const PRESTIGE_NODES = [
  // ── 중심 ──
  {
    id: 'genesis', name: '경지 개방 Ⅰ', branch: 'center', depth: 0, cost: 1, requires: null,
    desc: '위대한 모험가의 경지에 접어들다. 3차 전직 해금. 모든 가지 개방.',
    effect: { tier3unlock: true },
  },
  // ── 성장 가지 ──
  {
    id: 'growth_1', name: '수련의 기록 Ⅰ', branch: 'growth', depth: 1, cost: 1, requires: 'genesis',
    desc: '경험치 획득량 +25%',
    effect: { expBonus: 25 },
  },
  {
    id: 'growth_2', name: '수련의 기록 Ⅱ', branch: 'growth', depth: 2, cost: 2, requires: 'growth_1',
    desc: '경험치 획득량 추가 +35%',
    effect: { expBonus: 35 },
  },
  {
    id: 'growth_3', name: '길드의 번영', branch: 'growth', depth: 3, cost: 4, requires: 'growth_2',
    desc: '골드·재료 획득량 +25%',
    effect: { goldBonus: 25, materialBonus: 25 },
  },
  {
    id: 'growth_4', name: '황금 길드', branch: 'growth', depth: 4, cost: 7, requires: 'growth_3',
    desc: '골드·재료 획득량 추가 +35%',
    effect: { goldBonus: 35, materialBonus: 35 },
  },
  // ── 모험 가지 ──
  {
    id: 'venture_1', name: '선발대의 흔적', branch: 'venture', depth: 1, cost: 1, requires: 'genesis',
    desc: '파견 시작 시 진행도 +20',
    effect: { startProgress: 20 },
  },
  {
    id: 'venture_2', name: '지형 숙달', branch: 'venture', depth: 2, cost: 2, requires: 'venture_1',
    desc: '파견 시작 시 진행도 추가 +30',
    effect: { startProgress: 30 },
  },
  {
    id: 'venture_3', name: '베테랑의 감각', branch: 'venture', depth: 3, cost: 4, requires: 'venture_2',
    desc: '전투 승리 시 진행도 +1 추가',
    effect: { bonusProgress: 1 },
  },
  {
    id: 'venture_4', name: '전장의 영웅', branch: 'venture', depth: 4, cost: 7, requires: 'venture_3',
    desc: '보스 처치 시 진행도 추가 +3',
    effect: { bossProgress: 3 },
  },
  // ── 생존 가지 ──
  {
    id: 'survival_1', name: '강인한 육체 Ⅰ', branch: 'survival', depth: 1, cost: 1, requires: 'genesis',
    desc: '모험가 최대 HP +20%',
    effect: { hpBonus: 20 },
  },
  {
    id: 'survival_2', name: '단련된 방어', branch: 'survival', depth: 2, cost: 2, requires: 'survival_1',
    desc: '모험가 방어력 +20%',
    effect: { defBonus: 20 },
  },
  {
    id: 'survival_3', name: '사투의 경험', branch: 'survival', depth: 3, cost: 4, requires: 'survival_2',
    desc: '전멸 시 진행도 보존율 +25% (기본 50% → 75% 유지)',
    effect: { wipeRetain: 25 },
  },
  {
    id: 'survival_4', name: '강인한 육체 Ⅱ', branch: 'survival', depth: 4, cost: 7, requires: 'survival_3',
    desc: '모험가 최대 HP 추가 +30%, 방어력 추가 +15%',
    effect: { hpBonus: 30, defBonus: 15 },
  },
  // ── 경지 가지 ──
  {
    id: 'realm_2', name: '경지 개방 Ⅱ', branch: 'realm', depth: 1, cost: 5, requires: 'genesis',
    desc: '더 높은 경지에 이르다. 4차 전직 해금.',
    effect: { tier4unlock: true },
  },
  {
    id: 'realm_3', name: '경지 개방 Ⅲ', branch: 'realm', depth: 2, cost: 12, requires: 'realm_2',
    desc: '경지의 극점에 서다. 5차 전직 해금.',
    effect: { tier5unlock: true },
  },
];

// 연구소 제작 레시피
const LAB_RECIPES = [
  {
    id: 'book_일반',
    name: '경험치 서 [일반]',
    grade: '일반',
    icon: 'assets/items/I_Book.png',
    expValue: 1000,
    cost: { gold: 300, material: 3 },
    craftTime: 60,
    reqLabLv: 1,
  },
  {
    id: 'book_마법',
    name: '경험치 서 [마법]',
    grade: '마법',
    icon: 'assets/items/I_Book.png',
    expValue: 4000,
    cost: { gold: 1000, material: 10 },
    craftTime: 180,
    reqLabLv: 2,
  },
  {
    id: 'book_희귀',
    name: '경험치 서 [희귀]',
    grade: '희귀',
    icon: 'assets/items/I_Book.png',
    expValue: 15000,
    cost: { gold: 4000, material: 30 },
    craftTime: 480,
    reqLabLv: 4,
  },
  {
    id: 'book_영웅',
    name: '경험치 서 [영웅]',
    grade: '영웅',
    icon: 'assets/items/I_Book.png',
    expValue: 60000,
    cost: { gold: 15000, material: 90 },
    craftTime: 1200,
    reqLabLv: 6,
  },
  {
    id: 'book_전설',
    name: '경험치 서 [전설]',
    grade: '전설',
    icon: 'assets/items/I_Book.png',
    expValue: 200000,
    cost: { gold: 60000, material: 280 },
    craftTime: 3600,
    reqLabLv: 8,
  },
];

// 모험가 이름 풀
const ADVENTURER_NAMES = [
  '아리엘', '베른하르트', '클라우스', '도로테아', '에르빈',
  '프리다', '군터', '한나', '이고르', '야스민',
  '카를', '루이사', '마르쿠스', '노라', '오스카',
  '파울라', '퀸투스', '로사', '지그문트', '테레사',
  '울리히', '빌마', '크세르크세스', '이베트', '제노',
  '알베르트', '베아트리체', '코르넬리우스', '다이아나', '에마누엘',
  '펠리시타스', '고트프리트', '헬레나', '이사도라', '요한',
];

// 등급별 모험가 스탯 기준
const GRADE_STAT_MULT = {
  '일반': 1.0,
  '마법': 1.2,
  '희귀': 1.45,
  '영웅': 1.75,
  '전설': 2.1,
};

// 영구 단련 정의 (연구소, 리빌딩 후에도 유지)
const PERMANENT_TRAINING = [
  { id: 'hp',  name: '강인한 체력', icon: '❤️', stat: 'hp',  desc: '최대 HP +1%',  baseCost: 300000, costMult: 1.35 },
  { id: 'atk', name: '전투 훈련',   icon: '⚔️', stat: 'atk', desc: '공격력 +1%',   baseCost: 400000, costMult: 1.35 },
  { id: 'def', name: '방어 수련',   icon: '🛡️', stat: 'def', desc: '방어력 +1%',   baseCost: 350000, costMult: 1.35 },
];

// 경험치 테이블 (레벨당 필요 경험치)
function expRequired(level) {
  return Math.floor(100 * Math.pow(1.3, level - 1));
}

// 레벨별 스탯 성장
function statGrowth(baseStat, level, growthRate) {
  return Math.floor(baseStat * (1 + growthRate * (level - 1)));
}
